### ISSUE TITLE
Dev Container Build Failure

### ISSUE THREAD

**Issue by calderds** [gadgetron/gadgetron-starter#10]
OS: PopOS 22.04, NVIDIA GPU drivers. Cloned repository, reopened in dev container. Container construction failed with below error. 

```
#0 12.91 Setting up python3.8-minimal (3.8.10-0ubuntu1~20.04.8) ...

#0 13.00 Traceback (most recent call last):

#0 13.00   File "/usr/lib/python3.8/py_compile.py", line 215, in <module>

#0 13.00     sys.exit(main())
[2023-06-10T01:37:46.897Z] 
#0 13.00   File "/usr/lib/python3.8/py_compile.py", line 207, in main

#0 13.00     compile(filename, doraise=True)

#0 13.00   File "/usr/lib/python3.8/py_compile.py", line 172, in compile

#0 13.00     importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)

#0 13.00   File "<frozen importlib._bootstrap_external>", line 186, in _write_atomic

#0 13.00 PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/__pycache__/__future__.cpython-38.pyc.139716894588576'

#0 13.00 dpkg: error processing package python3.8-minimal (--configure):

#0 13.00  installed python3.8-minimal package post-installation script subprocess returned error exit status 1

#0 13.01 Errors were encountered while processing:

#0 13.01  python3.8-minimal

#0 13.02 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
[2023-06-10T01:37:46.897Z] ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/common_1 && chmod +x ./install.sh && ./install.sh]: exit code: 100
[2023-06-10T01:37:46.901Z] Stop (14193 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/vsch-calderds/container-features/0.245.2-1686361052630/Dockerfile-with-features -t vsc-gadgetron-starter-056c3c374dfa0779d7e7bb885ddee9a2 --target dev_containers_target_stage --cache-from ghcr.io/andrew-dupuis/gadgetron-starter/gadgetron_ubuntu_dev_cuda_oot:latest --build-context dev_containers_feature_content_source=/tmp/vsch-calderds/container-features/0.245.2-1686361052630 --build-arg _DEV_CONTAINERS_BASE_IMAGE=gadgetron_dev_cuda_oot --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/calderds/Projects/Coding/gadgetron-starter
[2023-06-10T01:37:46.903Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/vsch-calderds/container-features/0.245.2-1686361052630/Dockerfile-with-features -t vsc-gadgetron-starter-056c3c374dfa0779d7e7bb885ddee9a2 --target dev_containers_target_stage --cache-from ghcr.io/andrew-dupuis/gadgetron-starter/gadgetron_ubuntu_dev_cuda_oot:latest --build-context dev_containers_feature_content_source=/tmp/vsch-calderds/container-features/0.245.2-1686361052630 --build-arg _DEV_CONTAINERS_BASE_IMAGE=gadgetron_dev_cuda_oot --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/calderds/Projects/Coding/gadgetron-starter
[2023-06-10T01:37:46.903Z]     at HS (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:256:1490)
[2023-06-10T01:37:46.903Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-06-10T01:37:46.903Z]     at async Cu (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2801)
[2023-06-10T01:37:46.903Z]     at async Zw (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:1779)
[2023-06-10T01:37:46.903Z]     at async KS (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[2023-06-10T01:37:46.903Z]     at async co (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[2023-06-10T01:37:46.903Z]     at async LP (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[2023-06-10T01:37:46.903Z]     at async DP (/home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[2023-06-10T01:37:46.907Z] Stop (14500 ms): Run: /usr/share/code/code /home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/calderds/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/calderds/Projects/Coding/gadgetron-starter --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/calderds/Projects/Coding/gadgetron-starter --log-level debug --log-format json --config /home/calderds/Projects/Coding/gadgetron-starter/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-10T01:37:46.907Z] Exit code 1
[2023-06-10T01:37:46.911Z] Command failed: /usr/share/code/code /home/calderds/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/calderds/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/calderds/Projects/Coding/gadgetron-starter --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/calderds/Projects/Coding/gadgetron-starter --log-level debug --log-format json --config /home/calderds/Projects/Coding/gadgetron-starter/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-10T01:37:46.911Z] Exit code 1
```

**Comment by Andrew-Dupuis** [comment]
@calderds - what happens if you build with docker build . instead of using the .devcontainer? Do you still see this error? It may also be worth running a clean build for the devcontainer by avoiding using the build cache - you can comment out the lines in the devcontainer relating using the cached oot version of the docker base image. 

Also - what version of Docker, vscode, and the devcontainer extension are you using?

**Comment by calderds** [comment]
VSCode 1.67.2, Docker 24.0.2 (cb74dfc), Devcontainer extension 0.245.2. Trying the Docker build now, will update on the results.

**Comment by calderds** [comment]
Yep, docker build . works just fine

**Comment by calderds** [comment]
Tried commenting out the devcontainer oot line, but didn't fix the issue.

**Comment by Andrew-Dupuis** [comment]
> VSCode 1.67.2, Docker 24.0.2 (cb74dfc), Devcontainer extension 0.245.2. Trying the Docker build now, will update on the results.

I'm using VSCode 1.78.2, Devcontainer v0.296.0, but Docker 24.0.2 as well. There have been updates to the vscode  devcontainer interface, it may be worth updating there since the docker build itself works
